apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-service
spec:
  type: NodePort
  selector:
    app: breast-cancer-app
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30080  